config/routes.rb
Rails.application.routes.draw do

  resources :bookings
  devise_for :users
  get 'reservations/index'
  root to: 'bookings#new'
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :seat
	belongs_to :user
end

app/models/film.rb
class Film < ActiveRecord::Base
	has_many :shows
	has_many :bookings
	has_many :halls
end

app/models/hall.rb
class Hall < ActiveRecord::Base
	has_many :seats
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/models/seat.rb
class Seat < ActiveRecord::Base
	belongs_to :user
	belongs_to :hall
end

app/models/show.rb
class Show < ActiveRecord::Base
	belongs_to :hall
	belongs_to :film
	has_many :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :seat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  def index
  	@b= Booking.all.pluck(:reserved)
  end

  def new
  	@booking = Booking.new
  end

  def show
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def new
  	
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  def index
  	@b= Reservation.all.pluck(:reserved)
  end

  def create

  end

  def show
  	@reservation = Reservation.find(params[:id])	
  end

  def edit

  end

  def destroy

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/bookings/new.html.erb
<div class="container">
<h4>New Booking</h4>
<% if user_signed_in? %>
	<%= form_for @booking do |f| %>
		<div class="form-field">
    		<%= f.label :film_id %><br />
    		<%= f.collection_select :film_id, Film.order(:name), :id, :name, include_blank: true%>
  		</div>
		<div class="form-field">
    		<%= f.label :show_id, "Shows" %><br />
    		<%= f.grouped_collection_select :show_id, Film.order(:name), :shows, :name, :id, :time, include_blank: true %>
  		</div>
  		<%= link_to "Book Now", reservations_index_path, :class => 'btn btn-primary' %> 
  	<% end %>
<%else%>
  <p>Please <%= link_to "Login",  new_user_session_path %> to book your seat.</p>
<%end%>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		
		<title>Perspective Seat Preview</title>
		<%= stylesheet_link_tag    'application', media: 'all' %>
		<%= javascript_include_tag 'modernizr-custom' %>
		<%= csrf_meta_tags %>
	</head>
<nav>

    <div class="navbar navbar-inverse navbar-fixed-top">
   
    	<%= link_to image_tag("logo.png", :alt => "logo" ,  :height => 30, class:"brand-logo center"), "/" %>
      <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <% if user_signed_in? %>
  <%= link_to "Book Your Seat", new_booking_path %></li>
  <li class="nav-item">
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
<% else %>
 <li class="nav-item"><%= link_to "Log In", new_user_session_path %></li>
<% end %>
      </ul>
  </nav>
        
	<body>

		<p class="notice"><%= notice %></p>
       	<p class="alert"><%= alert %></p>

		<%= yield %>



		<%= javascript_include_tag 'application' %>


	</body>
</html>

app/views/reservations/show.html.erb
reservation#show